---
## Default Logstash configuration.

#The bind address for the HTTP API endpoint.
http.host: "0.0.0.0"

#Path to Logstash main pipeline config. This file is where we will define logs filter parse and transformations.
path.config: /usr/share/logstash/pipeline
